### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by jerry08** [Ozakinn/OzakiAnimeWPF#1]
You have a pretty neat project here. Why not consider using the MVVM approach? Would you like me to contribute to your project?

**Comment by Ozakinn** [comment]
Hi jerry08,
I started from Windows Form which by default does not have MVVM approach before.
This is my very first big project using WPF. Maybe, in the future I would use MVVM. I'm learning about MVVM Approach.
Actually, this project is supposedly personal. but my friends wants to use it.

Yes, you can contribute :)
If you see any problems that you think you can fix or a good feature to add.
(I might add discord RPC soon in my free time)

**Comment by jerry08** [comment]
Oh I see. I can help make a lot of improvements and make your code easier to understand. I can also implement the MVVM approach for you. Let me know as soon as you create your discord server. If you want, you can join mine https://discord.gg/mhxsSMy2Nf

**Comment by Ozakinn** [comment]
I'll be closing this now.
You can contact me on discord.

Thank you!
